#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#  for f in /etc/X11/xinit/xinitrc.d/*; do
#    [ -x "$f" ] && . "$f"
#  done
#  unset f
#fi


# run profile to set $PATH and other env vars correctly
. $HOME/.bash_profile

# setup background
xsetroot -solid '#056'

# setup mouse acceleration
xset m 7 2

# run initial programs
#xterm &

# start icewm, and run xterm if it crashes (just to be safe)
exec icewm || exec xterm -fg red

#exec dbus-launch mate-session
# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
